import chapter1Raw from './chapitre1.md?raw';
import chapter2Raw from './chapitre2.md?raw';
import chapter3Raw from './chapitre3.md?raw';
import chapter4Raw from './chapitre4.md?raw';
import chapter5Raw from './chapitre5.md?raw';
import chapter6Raw from './chapitre6.md?raw';
import chapter7Raw from './chapitre7.md?raw';
import chapter8Raw from './chapitre8.md?raw';
import chapter9Raw from './chapitre9.md?raw';
import chapter10Raw from './chapitre10.md?raw';
import chapter11Raw from './chapitre11.md?raw';
import chapter12Raw from './chapitre12.md?raw';
import chapter13Raw from './chapitre13.md?raw';
import chapter14Raw from './chapitre14.md?raw';
import chapter15Raw from './chapitre15.md?raw';
import chapter16Raw from './chapitre16.md?raw';
import chapter17Raw from './chapitre17.md?raw';
import chapter18Raw from './chapitre18.md?raw';
import chapter19Raw from './chapitre19.md?raw';
import chapter20Raw from './chapitre20.md?raw';
import chapter21Raw from './chapitre21.md?raw';
import chapter22Raw from './chapitre22.md?raw';
import chapter23Raw from './chapitre23.md?raw';
import chapter24Raw from './chapitre24.md?raw';

export const chapters = [
  {
    id: 'chapitre-1',
    slug: 'chapitre-1',
    number: 1,
    title: "Ouverture sensible",
    subtitle: "L'Anomalie du Quai & Le Comportement Non Conforme",
    act: "I",
    actTitle: "L'Anomalie",
    readTime: "7 min",
    readingTime: "7 min",
    path: "./chapitre1.md",
    synopsis: "Arrivée de Luna Mercier à Port-Mystral, première détection d'une adhérence anormale de l'eau sur la rampe des Terre-Neuvas et confrontation empirique avec Théo Delmas.",
    content: chapter1Raw,
  },
  {
    id: 'chapitre-2',
    slug: 'chapitre-2',
    number: 2,
    title: "Ce n’était pas pareil hier",
    subtitle: "Pointe de la Vigie & Le Protocole",
    act: "II",
    actTitle: "Enquête",
    readTime: "6 min",
    readingTime: "6 min",
    path: "./chapitre2.md",
    synopsis: "Dans le silence nocturne de Port-Mystral, Luna affronte le doute avant de prélever un échantillon à la Pointe de la Vigie. Rejointe par Théo Delmas, ils décident de contrer le discours officiel par un protocole expérimental irréfutable.",
    content: chapter2Raw,
  },
  {
    id: 'chapitre-3',
    slug: 'chapitre-3',
    number: 3,
    title: "Théo compte autrement",
    subtitle: "Vélocité terminale & L'épreuve d'Archimède",
    act: "II",
    actTitle: "Enquête",
    readTime: "6 min",
    readingTime: "6 min",
    path: "./chapitre3.md",
    synopsis: "Dans son atelier d'appentis, Théo met à l'épreuve l'échantillon de Luna : à 240 images par seconde, une bille d'acier accuse 0,32 seconde de retard. Face à l'aberration de la loi de Stokes, ils bravent le silence officiel pour porter leur mesure chez le Dr Archimède.",
    content: chapter3Raw,
  },
  {
    id: 'chapitre-4',
    slug: 'chapitre-4',
    number: 4,
    title: "Le bruit sous les mots",
    subtitle: "L'avis d'Archimède & La parole médiatique",
    act: "II",
    actTitle: "Enquête",
    readTime: "6 min",
    readingTime: "6 min",
    path: "./chapitre4.md",
    synopsis: "Dans son laboratoire, le Dr Archimède valide l'anomalie des 0,32 s mais prévient : face à Élise Tamar, un chiffre sans explication sera balayé. Sur le port et devant le Bar de la Marine, le mot « limon » anesthésie déjà la ville : le combat se joue désormais dans le langage.",
    content: chapter4Raw,
  },
  {
    id: 'chapitre-5',
    slug: 'chapitre-5',
    number: 5,
    title: "Le docteur Archimède ne répond pas…",
    subtitle: "L'anomalie dynamique & Le turbidimètre",
    act: "II",
    actTitle: "Enquête",
    readTime: "7 min",
    readingTime: "7 min",
    path: "./chapitre5.md",
    synopsis: "Dans son atelier, Archimède constate avec un densimètre que la masse volumique est normale mais que la dynamique des fluides est brisée. Après avoir confessé sa lâcheté passée envers le grand-père de Luna, il leur confie un turbidimètre de terrain et un carnet de papier pour démonter l'argument du limon d'Élise Tamar.",
    content: chapter5Raw,
  },
  {
    id: 'chapitre-6',
    slug: 'chapitre-6',
    number: 6,
    title: "Une version acceptable",
    subtitle: "La conférence de presse & Le carnet gris",
    act: "II",
    actTitle: "Enquête",
    readTime: "8 min",
    readingTime: "8 min",
    path: "./chapitre6.md",
    synopsis: "À la capitainerie, Élise Tamar impose sa version du limon d'équinoxe devant une ville rassurée par le mensonge. Rejetée par l'experte, Luna refuse de céder : dans l'ancien atelier de son grand-père, le frottement du graphite révèle une empreinte historique prouvant que la baie s'était déjà figée vingt ans plus tôt.",
    content: chapter6Raw,
  },
  {
    id: 'chapitre-7',
    slug: 'chapitre-7',
    number: 7,
    title: "Revenir avec une méthode",
    subtitle: "Le Protocole Alpha & La Matrice de la baie",
    act: "III",
    actTitle: "Résistance",
    readTime: "8 min",
    readingTime: "8 min",
    path: "./chapitre7.md",
    synopsis: "Réfugiés dans l'annexe oubliée d'Archimède, Luna et Théo transforment leur trouble en rigueur scientifique : division cartographique de la baie en 16 secteurs et premier prélèvement nocturne sous le belvédère de la mairie, où l'eau résiste au goulot malgré le froid.",
    content: chapter7Raw,
  },
  {
    id: 'chapitre-8',
    slug: 'chapitre-8',
    number: 8,
    title: "Ce qui se répète, ce qui change",
    subtitle: "La pulsation de douze minutes & L'alerte sociale",
    act: "III",
    actTitle: "Résistance",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre8.md",
    synopsis: "Épuisés par les prélèvements nocturnes de la Matrice, Luna et Théo découvrent que l'adhérence n'est pas aléatoire : elle suit une sinusoïde périodique de 12 minutes émanant de la fosse C3. Mais à l'aube, la grand-mère et la radio de Tamar opposent l'argument violent de la suggestion collective.",
    content: chapter8Raw,
  },
  {
    id: 'chapitre-9',
    slug: 'chapitre-9',
    number: 9,
    title: "Une hypothèse trop simple",
    subtitle: "L'épreuve de la digue & La rupture du modèle",
    act: "III",
    actTitle: "Résistance",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre9.md",
    synopsis: "Persuadé d'avoir dompté l'anomalie grâce à un modèle de résonance en cloche inversée au point C3, Théo tente une prédiction à la seconde près sur la digue de l'Est. L'échec cinglant et l'apparition d'une eau abrasive et chaotique forcent le duo à abandonner la mécanique simpliste pour explorer la géologie profonde.",
    content: chapter9Raw,
  },
  {
    id: 'chapitre-10',
    slug: 'chapitre-10',
    number: 10,
    title: "Ce que les grands-parents savaient...",
    subtitle: "Le Journal de bord du fond & L'infrastructure fantôme",
    act: "IV",
    actTitle: "L'Héritage",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre10.md",
    synopsis: "Guidée par sa grand-mère qui lui remet la clé de la remise, Luna exhume les carnets de 1994 de son aïeul. Avec Théo, ils découvrent que la pulsation n'est pas un mystère marin mais le spasme d'un vieux réseau de pompage dissimulé sous la fosse C3, dont la pression menace les scellés du Vieux Phare.",
    content: chapter10Raw,
  },
  {
    id: 'chapitre-11',
    slug: 'chapitre-11',
    number: 11,
    title: "La baie n’aime pas qu’on décide...",
    subtitle: "L'intensification physique & Le mur institutionnel",
    act: "IV",
    actTitle: "L'Héritage",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre11.md",
    synopsis: "En barque dans le secteur C2, Luna et Théo affrontent une eau bouillante à 28 °C et polymérisée en gelée sous leurs rames. Tandis que Tamar étouffe la panique sous l'alibi de poches de méthane et fait verrouiller le sentier des Douaniers par la mairie, les adolescents décident de s'infiltrer la nuit dans les grottes sous le Vieux Phare.",
    content: chapter11Raw,
  },
  {
    id: 'chapitre-12',
    slug: 'chapitre-12',
    number: 12,
    title: "Tamar parle pour tout le monde",
    subtitle: "Le choc des discours & La décision nocturne",
    act: "IV",
    actTitle: "L'Héritage",
    readTime: "10 min",
    readingTime: "10 min",
    path: "./chapitre12.md",
    synopsis: "Devant une salle comble et soulagée, Élise Tamar impose sa thèse rassurante d'un simple dégazage de vase et balaye l'objection d'Archimède. Ridiculisée au collège et confrontée au doute de Théo menacé par Morel, Luna maintient le cap : dans la nuit, Théo la rejoint à l'annexe pour braver l'interdit et s'infiltrer sous le Vieux Phare.",
    content: chapter12Raw,
  },
  {
    id: 'chapitre-13',
    slug: 'chapitre-13',
    number: 13,
    title: "Tenir les faits",
    subtitle: "L'interface souterraine & Le tri entre peur et indice",
    act: "V",
    actTitle: "La Preuve",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre13.md",
    synopsis: "Infiltrés sous les scellés du Vieux Phare à marée basse, Luna et Théo pénètrent dans la salle des machines fantôme et constatent un rejet d'eau bouillante à 32 °C. Pris en chasse par Morel, ils fuient par le conduit de décharge submergé et capturent au péril de leur vie la fréquence de 15 Hz de la pompe Goliath.",
    content: chapter13Raw,
  },
  {
    id: 'chapitre-14',
    slug: 'chapitre-14',
    number: 14,
    title: "Les zones qu’on contourne",
    subtitle: "La mémoire effacée & La limite de la preuve",
    act: "V",
    actTitle: "La Preuve",
    readTime: "10 min",
    readingTime: "10 min",
    path: "./chapitre14.md",
    synopsis: "En croisant le cadastre de 1992 et l'accident de 1996, Luna et Théo découvrent que la fondation Tamar utilise la baie comme radiateur clandestin pour stabiliser les fondations de la ville. Face au scepticisme municipal, Archimède leur confie une caméra thermique pour capturer le jet à 32 °C au récif des Brumes lors de la marée d'équinoxe de coefficient 104.",
    content: chapter14Raw,
  },
  {
    id: 'chapitre-15',
    slug: 'chapitre-15',
    number: 15,
    title: "Ce qui revient ne revient jamais pareil",
    subtitle: "L'équinoxe sur le récif & La double preuve",
    act: "V",
    actTitle: "La Preuve",
    readTime: "10 min",
    readingTime: "10 min",
    path: "./chapitre15.md",
    synopsis: "À 02h12 lors de l'équinoxe de coefficient 104 sur le récif des Brumes, Luna et Théo filment le jet thermique à 34 °C de la pompe Goliath et prélèvent un échantillon opalin fumant. Traqués par Morel et son quad, ils fuient par le sentier submergé pour mettre la preuve à l'abri dans la caisse en zinc du grand-père.",
    content: chapter15Raw,
  },
  {
    id: 'chapitre-16',
    slug: 'chapitre-16',
    number: 16,
    title: "Archimède reformule la question",
    subtitle: "L'arme sans manche & L'étau se resserre",
    act: "VI",
    actTitle: "L'Affrontement",
    readTime: "10 min",
    readingTime: "10 min",
    path: "./chapitre16.md",
    synopsis: "Dans son atelier, Archimède confirme le jet industriel à 34 °C et 15 Hz mais refuse l'éclat immédiat : une vérité brute sans stratégie ferait d'eux des coupables. Tandis qu'il les pousse à traquer le « pourquoi » du secret de 1996, un appel retentit : Élise Tamar s'est installée dans le salon de la grand-mère de Luna pour étouffer l'affaire.",
    content: chapter16Raw,
  },
  {
    id: 'chapitre-17',
    slug: 'chapitre-17',
    number: 17,
    title: "Bascule personnelle",
    subtitle: "La rupture du duo & Le poste de guet de la Pointe-Noire",
    act: "VI",
    actTitle: "L'Affrontement",
    readTime: "10 min",
    readingTime: "10 min",
    path: "./chapitre17.md",
    synopsis: "Refusant le compromis méthodologique de Théo qui remet son carnet à Tamar pour rentrer dans le rang, Luna affronte publiquement l'experte sur le port. Traitée d'orpheline instable en plein deuil, Luna trouve le soutien inattendu de sa grand-mère qui lui remet la clé secrète du poste de guet de la Pointe-Noire.",
    content: chapter17Raw,
  },
  {
    id: 'chapitre-18',
    slug: 'chapitre-18',
    number: 18,
    title: "La contradiction de trop",
    subtitle: "L'asphyxie de la preuve & Le point de non-retour",
    act: "VI",
    actTitle: "L'Affrontement",
    readTime: "10 min",
    readingTime: "10 min",
    path: "./chapitre18.md",
    synopsis: "Dans le bureau de Tamar, Théo refuse d'authentifier les relevés historiques de 1974 par peur du discrédit. Trahie par la capitainerie et isolée, Luna franchit seule la zone interdite de la Pointe-Noire sous la pluie : face aux vagues de sirop noir et au dôme vitreux, elle choisit l'abri clandestin et devient elle-même la preuve.",
    content: chapter18Raw,
  },
  {
    id: 'chapitre-19',
    slug: 'chapitre-19',
    number: 19,
    title: "Il n’y a plus de version simple",
    subtitle: "Le constat des décombres & La ré-alliance",
    act: "VII",
    actTitle: "La Résonance",
    readTime: "10 min",
    readingTime: "10 min",
    path: "./chapitre19.md",
    synopsis: "Devant le naufrage de leur enquête étouffée par le discours officiel de Tamar, Luna comprend grâce aux notes de 1974 que le phénomène est latent : il faut le convoquer par résonance plutôt que de l'attendre. Soutenue par sa grand-mère, elle retrouve Théo au Vieux-Môle pour sceller leur ré-alliance et pirater les balises du port.",
    content: chapter19Raw,
  },
  {
    id: 'chapitre-20',
    slug: 'chapitre-20',
    number: 20,
    title: "Les pièces se rejoignent",
    subtitle: "La relecture finale des traces & Le dispositif de preuve",
    act: "VII",
    actTitle: "La Résonance",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre20.md",
    synopsis: "En superposant le carnet de 1986 et ses relevés récents, Luna isole la constante critique des douze minutes et localise le foyer de l'adhérence entre la balise 4 et le récif des Pendus. Rejoint par Théo converti par l'évidence statistique, le duo conçoit avec le Dr Archimède un dispositif de mesure par dynamomètre et GPS pour arracher à la baie une preuve indiscutable.",
    content: chapter20Raw,
  },
  {
    id: 'chapitre-21',
    slug: 'chapitre-21',
    number: 21,
    title: "Ce qu’il faut risquer pour vérifier",
    subtitle: "La levée des doutes techniques & La convergence vers la baie",
    act: "VII",
    actTitle: "La Résonance",
    readTime: "10 min",
    readingTime: "10 min",
    path: "./chapitre21.md",
    synopsis: "Dans l'atelier d'Archimède, Théo dépasse ses réticences méthodologiques pour verrouiller le Capteur de Résistance Différentielle. Munie du dernier calque de 1996 transmis par sa grand-mère attestant la mémoire de forme de l'eau, Luna embarque de nuit avec Théo et Archimède sur la Méthode, bravant la surveillance de la gendarmerie et les caméras de Tamar pour mesurer l'anomalie en plein coefficient 108.",
    content: chapter21Raw,
  },
  {
    id: 'chapitre-22',
    slug: 'chapitre-22',
    number: 22,
    title: "Là où l’eau tient",
    subtitle: "L'approche du seuil & La manifestation irréfutable",
    act: "VIII",
    actTitle: "La Manifestation",
    readTime: "11 min",
    readingTime: "11 min",
    path: "./chapitre22.md",
    synopsis: "Descendus sur l'affleurement rocheux sous la digue nord, Luna, Théo et Archimède affrontent la marée montante. Témoin direct d'une vague noire qui s'élève comme un mur de verre et la cloue au sol par des filaments d'adhérence moléculaire sous les yeux d'Élise Tamar médusée, Luna soutient l'épreuve jusqu'à la rupture cristalline : la mesure physique est scellée, et le silence institutionnel définitivement rompu.",
    content: chapter22Raw,
  },
  {
    id: 'chapitre-23',
    slug: 'chapitre-23',
    number: 23,
    title: "Ce qui peut enfin être dit",
    subtitle: "La redistribution du savoir & L'alliance scellée",
    act: "VIII",
    actTitle: "La Manifestation",
    readTime: "11 min",
    readingTime: "11 min",
    path: "./chapitre23.md",
    synopsis: "Sur le quai n°4 où une chaîne reste suspendue à 45 degrés dans l'eau immobile, Luna et Théo imposent leurs relevés physiques à Élise Tamar face aux témoins. Lors d'un tête-à-tête sans fard à la capitainerie, l'experte capitule et intègre les données à son rapport officiel, avant que le laboratoire du Pr Chen ne valide la rupture de continuité : l'alliance entre mémoire, méthode et vérité est définitivement scellée.",
    content: chapter23Raw,
  },
  {
    id: 'chapitre-24',
    slug: 'chapitre-24',
    number: 24,
    title: "La discipline du regard",
    subtitle: "L’épreuve de la recevabilité & Ce qui demeure",
    act: "VIII",
    actTitle: "La Manifestation",
    readTime: "12 min",
    readingTime: "12 min",
    path: "./chapitre24.md",
    synopsis: "Dans la salle de réunion de la mairie, Luna, Théo et le Dr Archimède confrontent Élise Tamar aux côtés du Pr Chen. Face à la preuve statistique d'une viscosité multipliée par quatre sur huit capteurs et à la fiole d'eau à mémoire de tension, l'experte capitule et acte la reconnaissance officielle d'une Anomalie de Tension Locale. Sur la digue réconciliée au crépuscule, Luna et sa grand-mère scellent l'héritage d'une vérité désormais nommée et durable.",
    content: chapter24Raw,
  }
];

export default chapters;
