import chapter1Raw from './chapitre1.md?raw';
import chapter2Raw from './chapitre2.md?raw';
import chapter3Raw from './chapitre3.md?raw';
import chapter4Raw from './chapitre4.md?raw';
import chapter5Raw from './chapitre5.md?raw';
import chapter6Raw from './chapitre6.md?raw';
import chapter7Raw from './chapitre7.md?raw';
import chapter8Raw from './chapitre8.md?raw';
import chapter9Raw from './chapitre9.md?raw';
import chapter10Raw from './chapitre10.md?raw';
import chapter11Raw from './chapitre11.md?raw';
import chapter12Raw from './chapitre12.md?raw';
import chapter13Raw from './chapitre13.md?raw';

export const chapters = [
  {
    id: 'chapitre-1',
    slug: 'chapitre-1',
    number: 1,
    title: "Ouverture sensible",
    subtitle: "L'Anomalie du Quai & Le Comportement Non Conforme",
    act: "I",
    actTitle: "L'Anomalie",
    readTime: "7 min",
    readingTime: "7 min",
    path: "./chapitre1.md",
    synopsis: "Arrivée de Luna Mercier à Port-Mystral, première détection d'une adhérence anormale de l'eau sur la rampe des Terre-Neuvas et confrontation empirique avec Théo Delmas.",
    content: chapter1Raw,
  },
  {
    id: 'chapitre-2',
    slug: 'chapitre-2',
    number: 2,
    title: "Ce n’était pas pareil hier",
    subtitle: "Pointe de la Vigie & Le Protocole",
    act: "II",
    actTitle: "Enquête",
    readTime: "6 min",
    readingTime: "6 min",
    path: "./chapitre2.md",
    synopsis: "Dans le silence nocturne de Port-Mystral, Luna affronte le doute avant de prélever un échantillon à la Pointe de la Vigie. Rejointe par Théo Delmas, ils décident de contrer le discours officiel par un protocole expérimental irréfutable.",
    content: chapter2Raw,
  },
  {
    id: 'chapitre-3',
    slug: 'chapitre-3',
    number: 3,
    title: "Théo compte autrement",
    subtitle: "Vélocité terminale & L'épreuve d'Archimède",
    act: "II",
    actTitle: "Enquête",
    readTime: "6 min",
    readingTime: "6 min",
    path: "./chapitre3.md",
    synopsis: "Dans son atelier d'appentis, Théo met à l'épreuve l'échantillon de Luna : à 240 images par seconde, une bille d'acier accuse 0,32 seconde de retard. Face à l'aberration de la loi de Stokes, ils bravent le silence officiel pour porter leur mesure chez le Dr Archimède.",
    content: chapter3Raw,
  },
  {
    id: 'chapitre-4',
    slug: 'chapitre-4',
    number: 4,
    title: "Le bruit sous les mots",
    subtitle: "L'avis d'Archimède & La parole médiatique",
    act: "II",
    actTitle: "Enquête",
    readTime: "6 min",
    readingTime: "6 min",
    path: "./chapitre4.md",
    synopsis: "Dans son laboratoire, le Dr Archimède valide l'anomalie des 0,32 s mais prévient : face à Élise Tamar, un chiffre sans explication sera balayé. Sur le port et devant le Bar de la Marine, le mot « limon » anesthésie déjà la ville : le combat se joue désormais dans le langage.",
    content: chapter4Raw,
  },
  {
    id: 'chapitre-5',
    slug: 'chapitre-5',
    number: 5,
    title: "Le docteur Archimède ne répond pas…",
    subtitle: "L'anomalie dynamique & Le turbidimètre",
    act: "II",
    actTitle: "Enquête",
    readTime: "7 min",
    readingTime: "7 min",
    path: "./chapitre5.md",
    synopsis: "Dans son atelier, Archimède constate avec un densimètre que la masse volumique est normale mais que la dynamique des fluides est brisée. Après avoir confessé sa lâcheté passée envers le grand-père de Luna, il leur confie un turbidimètre de terrain et un carnet de papier pour démonter l'argument du limon d'Élise Tamar.",
    content: chapter5Raw,
  },
  {
    id: 'chapitre-6',
    slug: 'chapitre-6',
    number: 6,
    title: "Une version acceptable",
    subtitle: "La conférence de presse & Le carnet gris",
    act: "II",
    actTitle: "Enquête",
    readTime: "8 min",
    readingTime: "8 min",
    path: "./chapitre6.md",
    synopsis: "À la capitainerie, Élise Tamar impose sa version du limon d'équinoxe devant une ville rassurée par le mensonge. Rejetée par l'experte, Luna refuse de céder : dans l'ancien atelier de son grand-père, le frottement du graphite révèle une empreinte historique prouvant que la baie s'était déjà figée vingt ans plus tôt.",
    content: chapter6Raw,
  },
  {
    id: 'chapitre-7',
    slug: 'chapitre-7',
    number: 7,
    title: "Revenir avec une méthode",
    subtitle: "Le Protocole Alpha & La Matrice de la baie",
    act: "III",
    actTitle: "Résistance",
    readTime: "8 min",
    readingTime: "8 min",
    path: "./chapitre7.md",
    synopsis: "Réfugiés dans l'annexe oubliée d'Archimède, Luna et Théo transforment leur trouble en rigueur scientifique : division cartographique de la baie en 16 secteurs et premier prélèvement nocturne sous le belvédère de la mairie, où l'eau résiste au goulot malgré le froid.",
    content: chapter7Raw,
  },
  {
    id: 'chapitre-8',
    slug: 'chapitre-8',
    number: 8,
    title: "Ce qui se répète, ce qui change",
    subtitle: "La pulsation de douze minutes & L'alerte sociale",
    act: "III",
    actTitle: "Résistance",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre8.md",
    synopsis: "Épuisés par les prélèvements nocturnes de la Matrice, Luna et Théo découvrent que l'adhérence n'est pas aléatoire : elle suit une sinusoïde périodique de 12 minutes émanant de la fosse C3. Mais à l'aube, la grand-mère et la radio de Tamar opposent l'argument violent de la suggestion collective.",
    content: chapter8Raw,
  },
  {
    id: 'chapitre-9',
    slug: 'chapitre-9',
    number: 9,
    title: "Une hypothèse trop simple",
    subtitle: "L'épreuve de la digue & La rupture du modèle",
    act: "III",
    actTitle: "Résistance",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre9.md",
    synopsis: "Persuadé d'avoir dompté l'anomalie grâce à un modèle de résonance en cloche inversée au point C3, Théo tente une prédiction à la seconde près sur la digue de l'Est. L'échec cinglant et l'apparition d'une eau abrasive et chaotique forcent le duo à abandonner la mécanique simpliste pour explorer la géologie profonde.",
    content: chapter9Raw,
  },
  {
    id: 'chapitre-10',
    slug: 'chapitre-10',
    number: 10,
    title: "Ce que les grands-parents savaient...",
    subtitle: "Le Journal de bord du fond & L'infrastructure fantôme",
    act: "IV",
    actTitle: "L'Héritage",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre10.md",
    synopsis: "Guidée par sa grand-mère qui lui remet la clé de la remise, Luna exhume les carnets de 1994 de son aïeul. Avec Théo, ils découvrent que la pulsation n'est pas un mystère marin mais le spasme d'un vieux réseau de pompage dissimulé sous la fosse C3, dont la pression menace les scellés du Vieux Phare.",
    content: chapter10Raw,
  },
  {
    id: 'chapitre-11',
    slug: 'chapitre-11',
    number: 11,
    title: "La baie n’aime pas qu’on décide...",
    subtitle: "L'intensification physique & Le mur institutionnel",
    act: "IV",
    actTitle: "L'Héritage",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre11.md",
    synopsis: "En barque dans le secteur C2, Luna et Théo affrontent une eau bouillante à 28 °C et polymérisée en gelée sous leurs rames. Tandis que Tamar étouffe la panique sous l'alibi de poches de méthane et fait verrouiller le sentier des Douaniers par la mairie, les adolescents décident de s'infiltrer la nuit dans les grottes sous le Vieux Phare.",
    content: chapter11Raw,
  },
  {
    id: 'chapitre-12',
    slug: 'chapitre-12',
    number: 12,
    title: "Tamar parle pour tout le monde",
    subtitle: "Le choc des discours & La décision nocturne",
    act: "IV",
    actTitle: "L'Héritage",
    readTime: "10 min",
    readingTime: "10 min",
    path: "./chapitre12.md",
    synopsis: "Devant une salle comble et soulagée, Élise Tamar impose sa thèse rassurante d'un simple dégazage de vase et balaye l'objection d'Archimède. Ridiculisée au collège et confrontée au doute de Théo menacé par Morel, Luna maintient le cap : dans la nuit, Théo la rejoint à l'annexe pour braver l'interdit et s'infiltrer sous le Vieux Phare.",
    content: chapter12Raw,
  },
  {
    id: 'chapitre-13',
    slug: 'chapitre-13',
    number: 13,
    title: "Tenir les faits",
    subtitle: "L'interface souterraine & Le tri entre peur et indice",
    act: "V",
    actTitle: "La Preuve",
    readTime: "9 min",
    readingTime: "9 min",
    path: "./chapitre13.md",
    synopsis: "Infiltrés sous les scellés du Vieux Phare à marée basse, Luna et Théo pénètrent dans la salle des machines fantôme et constatent un rejet d'eau bouillante à 32 °C. Pris en chasse par Morel, ils fuient par le conduit de décharge submergé et capturent au péril de leur vie la fréquence de 15 Hz de la pompe Goliath.",
    content: chapter13Raw,
  }
];

export default chapters;
