import chapter1Raw from './chapitre1.md?raw';
import chapter2Raw from './chapitre2.md?raw';
import chapter3Raw from './chapitre3.md?raw';
import chapter4Raw from './chapitre4.md?raw';
import chapter5Raw from './chapitre5.md?raw';
import chapter6Raw from './chapitre6.md?raw';
import chapter7Raw from './chapitre7.md?raw';

export const chapters = [
  {
    id: 'chapitre-1',
    slug: 'chapitre-1',
    number: 1,
    title: "Ouverture sensible",
    subtitle: "L'Anomalie du Quai & Le Comportement Non Conforme",
    act: "I",
    actTitle: "L'Anomalie",
    readTime: "7 min",
    readingTime: "7 min",
    path: "./chapitre1.md",
    synopsis: "Arrivée de Luna Mercier à Port-Mystral, première détection d'une adhérence anormale de l'eau sur la rampe des Terre-Neuvas et confrontation empirique avec Théo Delmas.",
    content: chapter1Raw,
  },
  {
    id: 'chapitre-2',
    slug: 'chapitre-2',
    number: 2,
    title: "Ce n’était pas pareil hier",
    subtitle: "Pointe de la Vigie & Le Protocole",
    act: "II",
    actTitle: "Enquête",
    readTime: "6 min",
    readingTime: "6 min",
    path: "./chapitre2.md",
    synopsis: "Dans le silence nocturne de Port-Mystral, Luna affronte le doute avant de prélever un échantillon à la Pointe de la Vigie. Rejointe par Théo Delmas, ils décident de contrer le discours officiel par un protocole expérimental irréfutable.",
    content: chapter2Raw,
  },
  {
    id: 'chapitre-3',
    slug: 'chapitre-3',
    number: 3,
    title: "Théo compte autrement",
    subtitle: "Vélocité terminale & L'épreuve d'Archimède",
    act: "II",
    actTitle: "Enquête",
    readTime: "6 min",
    readingTime: "6 min",
    path: "./chapitre3.md",
    synopsis: "Dans son atelier d'appentis, Théo met à l'épreuve l'échantillon de Luna : à 240 images par seconde, une bille d'acier accuse 0,32 seconde de retard. Face à l'aberration de la loi de Stokes, ils bravent le silence officiel pour porter leur mesure chez le Dr Archimède.",
    content: chapter3Raw,
  },
  {
    id: 'chapitre-4',
    slug: 'chapitre-4',
    number: 4,
    title: "Le bruit sous les mots",
    subtitle: "L'avis d'Archimède & La parole médiatique",
    act: "II",
    actTitle: "Enquête",
    readTime: "6 min",
    readingTime: "6 min",
    path: "./chapitre4.md",
    synopsis: "Dans son laboratoire, le Dr Archimède valide l'anomalie des 0,32 s mais prévient : face à Élise Tamar, un chiffre sans explication sera balayé. Sur le port et devant le Bar de la Marine, le mot « limon » anesthésie déjà la ville : le combat se joue désormais dans le langage.",
    content: chapter4Raw,
  },
  {
    id: 'chapitre-5',
    slug: 'chapitre-5',
    number: 5,
    title: "Le docteur Archimède ne répond pas…",
    subtitle: "L'anomalie dynamique & Le turbidimètre",
    act: "II",
    actTitle: "Enquête",
    readTime: "7 min",
    readingTime: "7 min",
    path: "./chapitre5.md",
    synopsis: "Dans son atelier, Archimède constate avec un densimètre que la masse volumique est normale mais que la dynamique des fluides est brisée. Après avoir confessé sa lâcheté passée envers le grand-père de Luna, il leur confie un turbidimètre de terrain et un carnet de papier pour démonter l'argument du limon d'Élise Tamar.",
    content: chapter5Raw,
  },
  {
    id: 'chapitre-6',
    slug: 'chapitre-6',
    number: 6,
    title: "Une version acceptable",
    subtitle: "La conférence de presse & Le carnet gris",
    act: "II",
    actTitle: "Enquête",
    readTime: "8 min",
    readingTime: "8 min",
    path: "./chapitre6.md",
    synopsis: "À la capitainerie, Élise Tamar impose sa version du limon d'équinoxe devant une ville rassurée par le mensonge. Rejetée par l'experte, Luna refuse de céder : dans l'ancien atelier de son grand-père, le frottement du graphite révèle une empreinte historique prouvant que la baie s'était déjà figée vingt ans plus tôt.",
    content: chapter6Raw,
  },
  {
    id: 'chapitre-7',
    slug: 'chapitre-7',
    number: 7,
    title: "Revenir avec une méthode",
    subtitle: "Le Protocole Alpha & La Matrice de la baie",
    act: "III",
    actTitle: "Résistance",
    readTime: "8 min",
    readingTime: "8 min",
    path: "./chapitre7.md",
    synopsis: "Réfugiés dans l'annexe oubliée d'Archimède, Luna et Théo transforment leur trouble en rigueur scientifique : division cartographique de la baie en 16 secteurs et premier prélèvement nocturne sous le belvédère de la mairie, où l'eau résiste au goulot malgré le froid.",
    content: chapter7Raw,
  }
];

export default chapters;
